# -*- coding: utf-8 -*-
"""12_beginner_projects_in_python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1odRox_DD1s2_xzTyjQEhhpNrYH1FHWRB

#MadLibs Project
"""

youtuber="Md. Zahidur Rahman"
print("Subscribe to "+youtuber)
print("Subscribe to {}".format(youtuber))
print(f"Subscribe to {youtuber}")

adjective=input("How do you feel about programming?\n")
verb1=input("What do love about programming?\n")
verb2=input("How do you want to stay?\n")
famous=input("Who was the CEO of facebook?\n")
madlibs=f"computer programming is so {adjective}!!. It makes me so excited all the time because \ I love to do {verb1}. Stay cool and {verb2} like you are {famous}"
print(madlibs)

"""#Guess the number Project

"""

import random

def guess(value):
  random_num=random.randint(0,value)
  guess=0
  while(guess!=random_num):
    guess=int(input("Guess the Number : \n"))
    if guess>random_num:
      print("The number is too high")
    elif guess<random_num:
      print("The number is too low")
  print("Your guess is correct")
limit=int(input("Enter the value of highest limit for creating the random number"))
guess(limit)

import random
def computer_guess(value):
  low=0
  high=value
  feedback=''
  while feedback!='c':
    guess=random.randint(low,high)
    feedback=input(f"Is this the number {guess} correct? put 'h' for high , put 'l' for low , put 'c' for correct \n").lower()
    if feedback=='h':
      high=guess-1
    elif feedback=='l':
      low=guess+1
  print(f"yes your number is {guess} \n")
computer_guess(int(input("Please Enter upper limit : \n")))

import random

def play():
  user=input("Enter 'r' for : rock. Enter 'p' for : paper. Enter 's' scissors : \n").lower()
  computer=random.choice(['r','s','p'])
  print(computer)
  if user==computer:
    print("Tie")
  elif (player_is_win(user,computer)):
    print("You Win")
  else:
    print("Computer Win")

def player_is_win(user,computer):
  if(user=='r' and computer=='s') or (user=='s' and computer=='p') or (user=='p' and computer=='r'):
    return True
  return False
play()


#logic :
#r > s
#s > p
#p > s