# -*- coding: utf-8 -*-
"""12_beginner_projects_in_python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1odRox_DD1s2_xzTyjQEhhpNrYH1FHWRB

#MadLibs Project
"""

youtuber="Md. Zahidur Rahman"
print("Subscribe to "+youtuber)
print("Subscribe to {}".format(youtuber))
print(f"Subscribe to {youtuber}")

adjective=input("How do you feel about programming?\n")
verb1=input("What do love about programming?\n")
verb2=input("How do you want to stay?\n")
famous=input("Who was the CEO of facebook?\n")
madlibs=f"computer programming is so {adjective}!!. It makes me so excited all the time because \ I love to do {verb1}. Stay cool and {verb2} like you are {famous}"
print(madlibs)

"""#Guess the number Project

"""

import random

def guess(value):
  random_num=random.randint(0,value)
  guess=0
  while(guess!=random_num):
    guess=int(input("Guess the Number : \n"))
    if guess>random_num:
      print("The number is too high")
    elif guess<random_num:
      print("The number is too low")
  print("Your guess is correct")
guess(10)